AllCops:
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/**/*
    - config/**/*

Documentation:
  Enabled: false

LineLength:
  Max: 100

FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/initializers/*.rb

Style/EachWithObject:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/WordArray:
  Enabled: false

